#' plot_lengths
#'
#' wrapper function
#'
#' Pass a set of query and background genes along with a gene info, and the gene
#' lengths will be plotted
#'
#' @param plotting_data dataframe or vector containing numerical data
#' @param main title
#' @param dataset_names vector of names of the datasets in the plotting_data list, by default these are
#' taken from the column names of the dataframe
#'
#' @return produces a barplot and returns values generated by base function barplot.
#' @examples
#' bar_plot(chromosomes)
#' bar_plot(chromosomes, cex_names = 0.8, col=topo.colors(2), ylab="% of genes", xlab="chromosome")

#plot_lengths <- function(plotting_data, main="", xlab="",  ylab="%", las=1, dataset_names=colnames(plotting_data),
